### ISSUE TITLE
error when uploading the mobiperf website to the  server 

### ISSUE THREAD

**Issue by mezzeddine** [Mobiperf/Speedometer#4]
the message i got is below , i uploaded the website using Google App Engine Luncher..changed the App ID to mine..and removed the "tmpl" word from  app.yaml.tmpl

Traceback (most recent call last):
  File "/base/data/home/apps/s~tmoperf/1.359395346193444275/gspeedometer/wsgi.py", line 114, in **call**
    getattr(controller, action)(**kargs)
  File "/base/data/home/apps/s~tmoperf/1.359395346193444275/gspeedometer/controllers/home.py", line 63, in Dashboard
    'templates/home.html', template_args))
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/template.py", line 92, in render
    return t.render(Context(template_dict))
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/template.py", line 128, in wrap_render
    return orig_render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/**init**.py", line 173, in render
    return self._render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/__init__.py", line 167, in _render
    return self.nodelist.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/__init__.py", line 796, in render
    bits.append(self.render_node(node, context))
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/**init**.py", line 809, in render_node
    return node.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/loader_tags.py", line 103, in render
    compiled_parent = self.get_parent(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/loader_tags.py", line 100, in get_parent
    return get_template(parent)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/loader.py", line 157, in get_template
    template, origin = find_template(template_name)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html

**Comment by mdwelsh** [comment]
You can't just upload it the regular way, there is an update-server script which you have to use, which generates the files from the template and then uploads them. Only edit the .tmpl files.

**Comment by mdwelsh** [comment]
Edit the update_dev_server.sh and change the name of the server to your own. Then run that script, which will configure the templates and upload to AppEngine. I'll close this issue for now, re-open it if you have problems!

**Comment by mezzeddine** [comment]
Thanks mdwelsh for the respond..

I am using windows 7 computer--i don't have much experience working with  shell..can you please list the steps we need to successfully upload the website to the Google app engin...

the things i already have are--
1. google app engin ID
2. Google App Engin SDK

Thanks much

**Comment by mdwelsh** [comment]
I really don't know how to help with this other than to follow the instructions I gave you. More details on how to deploy AppEngine applications are here:

https://developers.google.com/appengine/docs/java/gettingstarted/uploading
